### ISSUE TITLE
Problems with android_tools_extract-utils repo

### ISSUE THREAD

**Issue by catellone** [crdroidandroid/android_tools_extract-utils#1]
When i do "repo init -u git://github.com/crdroidandroid/android.git -b 11.0" and then "repo sync" i got this:

fatal: Couldn't find remote ref refs/heads/lineage-18.1
crdroidandroid/android_tools_extract-utils:
fatal: Couldn't find remote ref refs/heads/lineage-18.1
crdroidandroid/android_tools_extract-utils: sleeping 4.0 seconds before retrying
fatal: Couldn't find remote ref refs/heads/lineage-18.1
crdroidandroid/android_tools_extract-utils:
fatal: Couldn't find remote ref refs/heads/lineage-18.1error: Cannot fetch crdroidandroid/android_tools_extract-utils from git://github.com/crdroidandroid/android_tools_extract-utils

Fetching: 100% (1/1), done in 4.228s
Garbage collecting: 100% (1/1), done in 0.004s
Checking out: 82% (704/856) crdroidandroid/android_system_securityerror: Cannot checkout crdroidandroid/android_tools_extract-utils: Man
ifestInvalidRevisionError: revision refs/heads/lineage-18.1 in crdroidandroid/android_tools_extract-utils not found
Checking out:  82% (704/856), done in 27.811s
error: in `sync`: revision refs/heads/lineage-18.1 in crdroidandroid/android_tools_extract-utils not found

and if i try to git clonte the repo i got this:

git clone https://github.com/crdroidandroid/android_tools_extract-utils.git -b 11.0
Cloning into 'android_tools_extract-utils'...
fatal: Remote branch 11 not found in upstream origin

**Comment by sileshn** [comment]
https://github.com/crdroidandroid/android/commit/fdcb8b07e858c86412768075f6ac04cf87dbd6af is missing remote in crdroid.xml
